[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/scribe-token"
  to = "/.netlify/functions/scribe-token"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
